// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
// Entry point Pulumi loads. Requires the compiled pack: no ts-node involved,
// which is what lets this run at all on TypeScript 7.
require("../lib/policy/pack").createPolicyPack();
